# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: USB UEFI Compatible
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Collection of guides for installing Linux to USB drive compatible with UEFI hosts
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://install-linux-guides.github.io" # the base hostname & protocol for your site, e.g. http://example.com
author: S0AndS0
twitter_username: S0_And_S0
github_username: install-linux-guides


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


## Thanks be to - https://jekyllrb.com/docs/collections/
collections:
  virtual-box:
    output: true
    permalink: /:collection/:name/
    order:
      - create-virtual-machine.md
      - virtual-machine-storage.md
      - virtual-machine-boot.md
      - virtual-machine-network.md
      - find-target-usb.md
      - start-virtual-machine.md
      - configure-live-boot.md
      - install-linux-to-usb.md
      - reboot-host-to-bios-menu.md
      - eufi-bootloader.md

  first-boot:
    output: true
    permalink: /:collection/:name/
    order:
      - upgrade.md
      - drivers.md
      - update-initramfs.md
      - configure-grub2.md
      - reboot.md


## liquid-utilities/include-attribution configuration defaults
attribution:
  title: Attribution
  class_prefix: attribution
  auto_font_awesome: true


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
